function outputString = transformation2static_transform_publisher(T_target_source, targetFrameName, sourceFrameName)
%transformation2static_transform_publisher Converts a transformation matrix to a ROS static transform publisher.

target_R_target_source = T_target_source(1:3,4);
Rot_traget_source = T_target_source(1:3,1:3);
q_target_source = rotm2quat(Rot_traget_source);
qw = q_target_source(1);
qx = q_target_source(2);
qy = q_target_source(3);
qz = q_target_source(4);

buffer = ['<node pkg="tf" type="static_transform_publisher"' ...
                ' name="%s_%s_broadcaster"' ...
                ' args="%.3f %.3f %.3f %.6f %.6f %.6f %.6f' ...
                ' %s %s 100" /> \n'];

outputString = sprintf(buffer, ...
        targetFrameName, sourceFrameName, ...
        target_R_target_source(1), target_R_target_source(2), target_R_target_source(3), ...
        qx, qy, qz, qw, ...
        targetFrameName, sourceFrameName);
end

